language: cpp
dist: trusty
sudo: false

compiler:
  - gcc


addons:
  apt:
    packages:
      - g++
      - libboost-dev
      - libboost-system-dev
      - libmicrohttpd-dev
      - libgphoto2-dev
      - libexif-dev

script:
  - make VERBOSE=1
