language: cpp

sudo: false

compiler:
  - gcc


addons:
  apt:
    packages:
      - g++
      - libboost-dev
      - libboost-system-dev
      - libmicrohttpd-dev
      - libghoto2-dev
      - libexif-dev

script:
  - make VERBOSE=1

